export const LOAD_CONNECT_DEVICES = 'LOAD_CONNECT_DEVICES';
export const GET_CONNECT_DEVICES = 'GET_CONNECT_DEVICES';

export const GET_CERTIFICATION_QUESTIONS = 'GET_CERTIFICATION_QUESTIONS';
export const GET_CERTIFICATIONS = 'GET_CERTIFICATIONS';
export const GET_CERTIFICATION_REPORT = 'GET_CERTIFICATION_REPORT';

export const GET_ORGANIZATION = 'GET_ORGANIZATION';

export const API_ERROR = 'API_ERROR';
export const DISMISS_API_ERROR = 'DISMISS_API_ERROR';

export const DISMISS_WARNING = 'DISMISS_WARNING';

export const DISMISS_API_BANNER = 'DISMISS_API_BANNER';
export const DISPLAY_API_BANNER = 'DISPLAY_API_BANNER';

// Certification sessions
export const START_CERT_SESSION = 'START_CERT_SESSION';
export const RESUME_CERT_SESSION = 'RESUME_CERT_SESSION';
export const CLEAR_CERT_SESSION = 'CLEAR_CERT_SESSION';
export const LOAD_CERT_SESSIONS = 'LOAD_CERT_SESSIONS';
export const SET_NO_DEVICE = 'SET_NO_DEVICE';

export const SELECT_DUT = 'SELECT_DUT';

// Tests
export const GET_TESTS = 'GET_TESTS';
export const GET_TEST_RESULTS = 'GET_TEST_RESULTS';
export const UPDATE_TEST_RESULTS = 'UPDATE_TEST_RESULTS';
export const STOP_RUNNING_TESTS = 'STOP_RUNNING_TESTS';
export const CLOSE_PROMPT = 'CLOSE_PROMPT';

// Submission form actions
export const TEXTFIELD_DID_CHANGE = 'TEXTFIELD_DID_CHANGE';
export const CHECKBOX_CHANGE = 'CHECKBOX_CHANGE';
export const GET_SUBMISSION_FIELDS = 'GET_SUBMISSION_FIELDS';

// Submission form text fields
export const TEXTFIELD_FIRSTNAME = 'TEXTFIELD_FIRSTNAME';
export const TEXTFIELD_LASTNAME = 'TEXTFIELD_LASTNAME';
export const TEXTFIELD_EMAIL = 'TEXTFIELD_EMAIL';
export const TEXTFIELD_COMPANY = 'TEXTFIELD_COMPANY';
export const TEXTFIELD_FWVERSION = 'TEXTFIELD_FWVERSION';

// Harmony player
export const PLAYER_CONTEXT_PLAYER_STATE_CHANGED = 'PLAYER_CONTEXT_PLAYER_STATE_CHANGED';
export const LAST_ACTIVE_DEVICE_INFO_CHANGED = 'LAST_ACTIVE_DEVICE_INFO_CHANGED';
export const TRACK_PROGRESS_CHANGED = 'TRACK_PROGRESS_CHANGED';

// User
export const GET_USER_INFO = 'GET_USER_INFO';
