export const FETCH_PAYMENT_DETAILS = 'FETCH_PAYMENT_DETAILS';
export const FETCH_PAYMENT_DETAILS_SUCCESS = 'FETCH_PAYMENT_DETAILS_SUCCESS';
export const FETCH_PAYMENT_DETAILS_FAILED = 'FETCH_PAYMENT_DETAILS_FAILED';
