export const FETCH_AUDIENCE_SEGMENTS_REQUESTED =
  'FETCH_AUDIENCE_SEGMENTS_REQUESTED';
export const FETCH_AUDIENCE_SEGMENTS_SUCCEEDED =
  'FETCH_AUDIENCE_SEGMENTS_SUCCEEDED';
export const FETCH_AUDIENCE_SEGMENTS_FAILED = 'FETCH_AUDIENCE_SEGMENTS_FAILED';

export const FETCH_MOMENTS_REQUESTED = 'FETCH_MOMENTS_REQUESTED';
export const FETCH_MOMENTS_SUCCEEDED = 'FETCH_MOMENTS_SUCCEEDED';
export const FETCH_MOMENTS_FAILED = 'FETCH_MOMENTS_FAILED';

export const FETCH_VOICEOVER_OPTIONS_REQUESTED =
  'FETCH_VOICEOVER_OPTIONS_REQUESTED';
export const FETCH_VOICEOVER_OPTIONS_SUCCEEDED =
  'FETCH_VOICEOVER_OPTIONS_SUCCEEDED';
export const FETCH_VOICEOVER_OPTIONS_FAILED = 'FETCH_VOICEOVER_OPTIONS_FAILED';

export const FETCH_CTA_OPTIONS_REQUESTED = 'FETCH_CTA_OPTIONS_REQUESTED';
export const FETCH_CTA_OPTIONS_SUCCEEDED = 'FETCH_CTA_OPTIONS_SUCCEEDED';
export const FETCH_CTA_OPTIONS_FAILED = 'FETCH_CTA_OPTIONS_FAILED';

export const FETCH_STOCK_COMPANION_IMAGES_REQUESTED =
  'FETCH_STOCK_COMPANION_IMAGES_REQUESTED';
export const FETCH_STOCK_COMPANION_IMAGES_SUCCEEDED =
  'FETCH_STOCK_COMPANION_IMAGES_SUCCEEDED';
export const FETCH_STOCK_COMPANION_IMAGES_FAILED =
  'FETCH_STOCK_COMPANION_IMAGES_FAILED';

export const FETCH_CATEGORIES_REQUESTED = 'FETCH_CATEGORIES_REQUESTED';
export const FETCH_CATEGORIES_SUCCEEDED = 'FETCH_CATEGORIES_SUCCEEDED';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';
