export const SET_REDIRECTING = 'SET_REDIRECTING';
export const STORE_REDIRECT_VALUES = 'STORE_REDIRECT_VALUES';
export const REDIRECT_FROM_STORAGE = 'REDIRECT_FROM_STORAGE';
export const CLEAR_REDIRECT_FROM_STORAGE = 'CLEAR_REDIRECT_FROM_STORAGE';
