export const AUTHORIZED_SESSION_ACTIVE = 'AUTHORIZED_SESSION_ACTIVE';
export const AUTHORIZED_SESSION_INACTIVE = 'AUTHORIZED_SESSION_INACTIVE';
export const SSO_SESSION_ACTIVE = 'SSO_SESSION_ACTIVE';
export const SSO_SESSION_INACTIVE = 'SSO_SESSION_INACTIVE';
export const SSO_SESSION_ERROR = 'SSO_SESSION_ERROR';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
