export const MIX_PREVIEW_SUBMITTED = 'MIX_PREVIEW_SUBMITTED';
export const MIX_PREVIEW_SUCCEEDED = 'MIX_PREVIEW_SUCCEEDED';
export const MIX_PREVIEW_FAILED = 'MIX_PREVIEW_FAILED';
export const MIX_PREVIEW_CLEAR = 'MIX_PREVIEW_CLEAR';
export const MIX_PREVIEW_FAILED_MISSING_MUSIC =
  'MIX_PREVIEW_FAILED_MISSING_MUSIC';

export const MIX_HISTORY_REQUESTED = 'MIX_HISTORY_REQUESTED';
export const MIX_HISTORY_SUCCEEDED = 'MIX_HISTORY_SUCCEEDED';
export const MIX_HISTORY_FAILED = 'MIX_HISTORY_FAILED';
