import { useT } from '@mrkt/features/i18n';

export type CountryNamesKeys = keyof ReturnType<typeof useCountryNames>;

export function useCountryNames() {
  const t = useT();

  return {
    AF: t('COUNTRY_NAME_AF', 'Afghanistan', 'Name of country'),
    AX: t('COUNTRY_NAME_AX', 'Aland Islands', 'Name of country'),
    AL: t('COUNTRY_NAME_AL', 'Albania', 'Name of country'),
    DZ: t('COUNTRY_NAME_DZ', 'Algeria', 'Name of country'),
    AS: t('COUNTRY_NAME_AS', 'American Samoa', 'Name of country'),
    AD: t('COUNTRY_NAME_AD', 'Andorra', 'Name of country'),
    AO: t('COUNTRY_NAME_AO', 'Angola', 'Name of country'),
    AI: t('COUNTRY_NAME_AI', 'Anguilla', 'Name of country'),
    AQ: t('COUNTRY_NAME_AQ', 'Antarctica', 'Name of country'),
    AG: t('COUNTRY_NAME_AG', 'Antigua And Barbuda', 'Name of country'),
    AR: t('COUNTRY_NAME_AR', 'Argentina', 'Name of country'),
    AM: t('COUNTRY_NAME_AM', 'Armenia', 'Name of country'),
    AW: t('COUNTRY_NAME_AW', 'Aruba', 'Name of country'),
    AU: t('COUNTRY_NAME_AU', 'Australia', 'Name of country'),
    AT: t('COUNTRY_NAME_AT', 'Austria', 'Name of country'),
    AZ: t('COUNTRY_NAME_AZ', 'Azerbaijan', 'Name of country'),
    BS: t('COUNTRY_NAME_BS', 'Bahamas', 'Name of country'),
    BH: t('COUNTRY_NAME_BH', 'Bahrain', 'Name of country'),
    BD: t('COUNTRY_NAME_BD', 'Bangladesh', 'Name of country'),
    BB: t('COUNTRY_NAME_BB', 'Barbados', 'Name of country'),
    BY: t('COUNTRY_NAME_BY', 'Belarus', 'Name of country'),
    BE: t('COUNTRY_NAME_BE', 'Belgium', 'Name of country'),
    BZ: t('COUNTRY_NAME_BZ', 'Belize', 'Name of country'),
    BJ: t('COUNTRY_NAME_BJ', 'Benin', 'Name of country'),
    BM: t('COUNTRY_NAME_BM', 'Bermuda', 'Name of country'),
    BT: t('COUNTRY_NAME_BT', 'Bhutan', 'Name of country'),
    BO: t('COUNTRY_NAME_BO', 'Bolivia', 'Name of country'),
    BA: t('COUNTRY_NAME_BA', 'Bosnia And Herzegovina', 'Name of country'),
    BW: t('COUNTRY_NAME_BW', 'Botswana', 'Name of country'),
    BV: t('COUNTRY_NAME_BV', 'Bouvet Island', 'Name of country'),
    BR: t('COUNTRY_NAME_BR', 'Brazil', 'Name of country'),
    IO: t(
      'COUNTRY_NAME_IO',
      'British Indian Ocean Territory',
      'Name of country',
    ),
    BN: t('COUNTRY_NAME_BN', 'Brunei Darussalam', 'Name of country'),
    BG: t('COUNTRY_NAME_BG', 'Bulgaria', 'Name of country'),
    BF: t('COUNTRY_NAME_BF', 'Burkina Faso', 'Name of country'),
    BI: t('COUNTRY_NAME_BI', 'Burundi', 'Name of country'),
    KH: t('COUNTRY_NAME_KH', 'Cambodia', 'Name of country'),
    CM: t('COUNTRY_NAME_CM', 'Cameroon', 'Name of country'),
    CA: t('COUNTRY_NAME_CA', 'Canada', 'Name of country'),
    CV: t('COUNTRY_NAME_CV', 'Cabo Verde', 'Name of country'),
    KY: t('COUNTRY_NAME_KY', 'Cayman Islands', 'Name of country'),
    CF: t('COUNTRY_NAME_CF', 'Central African Republic', 'Name of country'),
    TD: t('COUNTRY_NAME_TD', 'Chad', 'Name of country'),
    CL: t('COUNTRY_NAME_CL', 'Chile', 'Name of country'),
    CN: t('COUNTRY_NAME_CN', 'China', 'Name of country'),
    CX: t('COUNTRY_NAME_CX', 'Christmas Island', 'Name of country'),
    CC: t('COUNTRY_NAME_CC', 'Cocos (Keeling) Islands', 'Name of country'),
    CO: t('COUNTRY_NAME_CO', 'Colombia', 'Name of country'),
    KM: t('COUNTRY_NAME_KM', 'Comoros', 'Name of country'),
    CG: t('COUNTRY_NAME_CG', 'Republic of the Congo', 'Name of country'),
    CD: t(
      'COUNTRY_NAME_CD',
      'Democratic Republic of the Congo',
      'Name of country',
    ),
    CK: t('COUNTRY_NAME_CK', 'Cook Islands', 'Name of country'),
    CR: t('COUNTRY_NAME_CR', 'Costa Rica', 'Name of country'),
    CI: t('COUNTRY_NAME_CI', "Côte d'Ivoire", 'Name of country'),
    CW: t('COUNTRY_NAME_CW', 'Curacao', 'Name of country'),
    HR: t('COUNTRY_NAME_HR', 'Croatia', 'Name of country'),
    CU: t('COUNTRY_NAME_CU', 'Cuba', 'Name of country'),
    CY: t('COUNTRY_NAME_CY', 'Cyprus', 'Name of country'),
    CZ: t('COUNTRY_NAME_CZ', 'Czech Republic', 'Name of country'),
    DK: t('COUNTRY_NAME_DK', 'Denmark', 'Name of country'),
    DJ: t('COUNTRY_NAME_DJ', 'Djibouti', 'Name of country'),
    DM: t('COUNTRY_NAME_DM', 'Dominica', 'Name of country'),
    DO: t('COUNTRY_NAME_DO', 'Dominican Republic', 'Name of country'),
    EC: t('COUNTRY_NAME_EC', 'Ecuador', 'Name of country'),
    EG: t('COUNTRY_NAME_EG', 'Egypt', 'Name of country'),
    SV: t('COUNTRY_NAME_SV', 'El Salvador', 'Name of country'),
    GQ: t('COUNTRY_NAME_GQ', 'Equatorial Guinea', 'Name of country'),
    ER: t('COUNTRY_NAME_ER', 'Eritrea', 'Name of country'),
    EE: t('COUNTRY_NAME_EE', 'Estonia', 'Name of country'),
    ET: t('COUNTRY_NAME_ET', 'Ethiopia', 'Name of country'),
    FK: t('COUNTRY_NAME_FK', 'Falkland Islands (Malvinas)', 'Name of country'),
    FO: t('COUNTRY_NAME_FO', 'Faroe Islands', 'Name of country'),
    FJ: t('COUNTRY_NAME_FJ', 'Fiji', 'Name of country'),
    FI: t('COUNTRY_NAME_FI', 'Finland', 'Name of country'),
    FR: t('COUNTRY_NAME_FR', 'France', 'Name of country'),
    GF: t('COUNTRY_NAME_GF', 'French Guiana', 'Name of country'),
    PF: t('COUNTRY_NAME_PF', 'French Polynesia', 'Name of country'),
    TF: t('COUNTRY_NAME_TF', 'French Southern Territories', 'Name of country'),
    GA: t('COUNTRY_NAME_GA', 'Gabon', 'Name of country'),
    GM: t('COUNTRY_NAME_GM', 'Gambia', 'Name of country'),
    GE: t('COUNTRY_NAME_GE', 'Georgia', 'Name of country'),
    DE: t('COUNTRY_NAME_DE', 'Germany', 'Name of country'),
    GH: t('COUNTRY_NAME_GH', 'Ghana', 'Name of country'),
    GI: t('COUNTRY_NAME_GI', 'Gibraltar', 'Name of country'),
    GR: t('COUNTRY_NAME_GR', 'Greece', 'Name of country'),
    GL: t('COUNTRY_NAME_GL', 'Greenland', 'Name of country'),
    GD: t('COUNTRY_NAME_GD', 'Grenada', 'Name of country'),
    GP: t('COUNTRY_NAME_GP', 'Guadeloupe', 'Name of country'),
    GU: t('COUNTRY_NAME_GU', 'Guam', 'Name of country'),
    GT: t('COUNTRY_NAME_GT', 'Guatemala', 'Name of country'),
    GG: t('COUNTRY_NAME_GG', 'Guernsey', 'Name of country'),
    GN: t('COUNTRY_NAME_GN', 'Guinea', 'Name of country'),
    GW: t('COUNTRY_NAME_GW', 'Guinea-Bissau', 'Name of country'),
    GY: t('COUNTRY_NAME_GY', 'Guyana', 'Name of country'),
    HT: t('COUNTRY_NAME_HT', 'Haiti', 'Name of country'),
    HM: t(
      'COUNTRY_NAME_HM',
      'Heard Island & Mcdonald Islands',
      'Name of country',
    ),
    VA: t(
      'COUNTRY_NAME_VA',
      'Holy See (Vatican City State)',
      'Name of country',
    ),
    HN: t('COUNTRY_NAME_HN', 'Honduras', 'Name of country'),
    HK: t('COUNTRY_NAME_HK', 'Hong Kong', 'Name of country'),
    HU: t('COUNTRY_NAME_HU', 'Hungary', 'Name of country'),
    IS: t('COUNTRY_NAME_IS', 'Iceland', 'Name of country'),
    IN: t('COUNTRY_NAME_IN', 'India', 'Name of country'),
    ID: t('COUNTRY_NAME_ID', 'Indonesia', 'Name of country'),
    IR: t('COUNTRY_NAME_IR', 'Iran, Islamic Republic Of', 'Name of country'),
    IQ: t('COUNTRY_NAME_IQ', 'Iraq', 'Name of country'),
    IE: t('COUNTRY_NAME_IE', 'Ireland', 'Name of country'),
    IM: t('COUNTRY_NAME_IM', 'Isle Of Man', 'Name of country'),
    IL: t('COUNTRY_NAME_IL', 'Israel', 'Name of country'),
    IT: t('COUNTRY_NAME_IT', 'Italy', 'Name of country'),
    JM: t('COUNTRY_NAME_JM', 'Jamaica', 'Name of country'),
    JP: t('COUNTRY_NAME_JP', 'Japan', 'Name of country'),
    JE: t('COUNTRY_NAME_JE', 'Jersey', 'Name of country'),
    JO: t('COUNTRY_NAME_JO', 'Jordan', 'Name of country'),
    KZ: t('COUNTRY_NAME_KZ', 'Kazakhstan', 'Name of country'),
    KE: t('COUNTRY_NAME_KE', 'Kenya', 'Name of country'),
    KI: t('COUNTRY_NAME_KI', 'Kiribati', 'Name of country'),
    KR: t('COUNTRY_NAME_KR', 'South Korea', 'Name of country'),
    XK: t('COUNTRY_NAME_XK', 'Kosovo', 'Name of country'),
    KW: t('COUNTRY_NAME_KW', 'Kuwait', 'Name of country'),
    KG: t('COUNTRY_NAME_KG', 'Kyrgyzstan', 'Name of country'),
    LA: t(
      'COUNTRY_NAME_LA',
      "Lao People's Democratic Republic",
      'Name of country',
    ),
    LV: t('COUNTRY_NAME_LV', 'Latvia', 'Name of country'),
    LB: t('COUNTRY_NAME_LB', 'Lebanon', 'Name of country'),
    LS: t('COUNTRY_NAME_LS', 'Lesotho', 'Name of country'),
    LR: t('COUNTRY_NAME_LR', 'Liberia', 'Name of country'),
    LY: t('COUNTRY_NAME_LY', 'Libya', 'Name of country'),
    LI: t('COUNTRY_NAME_LI', 'Liechtenstein', 'Name of country'),
    LT: t('COUNTRY_NAME_LT', 'Lithuania', 'Name of country'),
    LU: t('COUNTRY_NAME_LU', 'Luxembourg', 'Name of country'),
    MO: t('COUNTRY_NAME_MO', 'Macau', 'Name of country'),
    MK: t('COUNTRY_NAME_MK', 'North Macedonia', 'Name of country'),
    MG: t('COUNTRY_NAME_MG', 'Madagascar', 'Name of country'),
    MW: t('COUNTRY_NAME_MW', 'Malawi', 'Name of country'),
    MY: t('COUNTRY_NAME_MY', 'Malaysia', 'Name of country'),
    MV: t('COUNTRY_NAME_MV', 'Maldives', 'Name of country'),
    ML: t('COUNTRY_NAME_ML', 'Mali', 'Name of country'),
    MT: t('COUNTRY_NAME_MT', 'Malta', 'Name of country'),
    MH: t('COUNTRY_NAME_MH', 'Marshall Islands', 'Name of country'),
    MQ: t('COUNTRY_NAME_MQ', 'Martinique', 'Name of country'),
    MR: t('COUNTRY_NAME_MR', 'Mauritania', 'Name of country'),
    MU: t('COUNTRY_NAME_MU', 'Mauritius', 'Name of country'),
    YT: t('COUNTRY_NAME_YT', 'Mayotte', 'Name of country'),
    MX: t('COUNTRY_NAME_MX', 'Mexico', 'Name of country'),
    FM: t('COUNTRY_NAME_FM', 'Micronesia', 'Name of country'),
    MD: t('COUNTRY_NAME_MD', 'Moldova', 'Name of country'),
    MC: t('COUNTRY_NAME_MC', 'Monaco', 'Name of country'),
    MN: t('COUNTRY_NAME_MN', 'Mongolia', 'Name of country'),
    ME: t('COUNTRY_NAME_ME', 'Montenegro', 'Name of country'),
    MS: t('COUNTRY_NAME_MS', 'Montserrat', 'Name of country'),
    MA: t('COUNTRY_NAME_MA', 'Morocco', 'Name of country'),
    MZ: t('COUNTRY_NAME_MZ', 'Mozambique', 'Name of country'),
    MM: t('COUNTRY_NAME_MM', 'Myanmar', 'Name of country'),
    NA: t('COUNTRY_NAME_NA', 'Namibia', 'Name of country'),
    NR: t('COUNTRY_NAME_NR', 'Nauru', 'Name of country'),
    NP: t('COUNTRY_NAME_NP', 'Nepal', 'Name of country'),
    NL: t('COUNTRY_NAME_NL', 'Netherlands', 'Name of country'),
    AN: t('COUNTRY_NAME_AN', 'Netherlands Antilles', 'Name of country'),
    NC: t('COUNTRY_NAME_NC', 'New Caledonia', 'Name of country'),
    NZ: t('COUNTRY_NAME_NZ', 'New Zealand', 'Name of country'),
    NI: t('COUNTRY_NAME_NI', 'Nicaragua', 'Name of country'),
    NE: t('COUNTRY_NAME_NE', 'Niger', 'Name of country'),
    NG: t('COUNTRY_NAME_NG', 'Nigeria', 'Name of country'),
    NU: t('COUNTRY_NAME_NU', 'Niue', 'Name of country'),
    NF: t('COUNTRY_NAME_NF', 'Norfolk Island', 'Name of country'),
    MP: t('COUNTRY_NAME_MP', 'Northern Mariana Islands', 'Name of country'),
    NO: t('COUNTRY_NAME_NO', 'Norway', 'Name of country'),
    OM: t('COUNTRY_NAME_OM', 'Oman', 'Name of country'),
    PK: t('COUNTRY_NAME_PK', 'Pakistan', 'Name of country'),
    PW: t('COUNTRY_NAME_PW', 'Palau', 'Name of country'),
    PS: t('COUNTRY_NAME_PS', 'Palestinian Territories', 'Name of country'),
    PA: t('COUNTRY_NAME_PA', 'Panama', 'Name of country'),
    PG: t('COUNTRY_NAME_PG', 'Papua New Guinea', 'Name of country'),
    PY: t('COUNTRY_NAME_PY', 'Paraguay', 'Name of country'),
    PE: t('COUNTRY_NAME_PE', 'Peru', 'Name of country'),
    PH: t('COUNTRY_NAME_PH', 'Philippines', 'Name of country'),
    PN: t('COUNTRY_NAME_PN', 'Pitcairn', 'Name of country'),
    PL: t('COUNTRY_NAME_PL', 'Poland', 'Name of country'),
    PT: t('COUNTRY_NAME_PT', 'Portugal', 'Name of country'),
    PR: t('COUNTRY_NAME_PR', 'Puerto Rico', 'Name of country'),
    QA: t('COUNTRY_NAME_QA', 'Qatar', 'Name of country'),
    RE: t('COUNTRY_NAME_RE', 'Reunion', 'Name of country'),
    RO: t('COUNTRY_NAME_RO', 'Romania', 'Name of country'),
    RU: t('COUNTRY_NAME_RU', 'Russian Federation', 'Name of country'),
    RW: t('COUNTRY_NAME_RW', 'Rwanda', 'Name of country'),
    BL: t('COUNTRY_NAME_BL', 'St. Barthelemy', 'Name of country'),
    SH: t('COUNTRY_NAME_SH', 'St. Helena', 'Name of country'),
    KN: t('COUNTRY_NAME_KN', 'St. Kitts And Nevis', 'Name of country'),
    LC: t('COUNTRY_NAME_LC', 'St. Lucia', 'Name of country'),
    MF: t('COUNTRY_NAME_MF', 'St. Martin', 'Name of country'),
    PM: t('COUNTRY_NAME_PM', 'St. Pierre And Miquelon', 'Name of country'),
    VC: t('COUNTRY_NAME_VC', 'St. Vincent And Grenadines', 'Name of country'),
    WS: t('COUNTRY_NAME_WS', 'Samoa', 'Name of country'),
    SM: t('COUNTRY_NAME_SM', 'San Marino', 'Name of country'),
    ST: t('COUNTRY_NAME_ST', 'Sao Tome And Principe', 'Name of country'),
    SA: t('COUNTRY_NAME_SA', 'Saudi Arabia', 'Name of country'),
    SN: t('COUNTRY_NAME_SN', 'Senegal', 'Name of country'),
    RS: t('COUNTRY_NAME_RS', 'Serbia', 'Name of country'),
    SC: t('COUNTRY_NAME_SC', 'Seychelles', 'Name of country'),
    SL: t('COUNTRY_NAME_SL', 'Sierra Leone', 'Name of country'),
    SG: t('COUNTRY_NAME_SG', 'Singapore', 'Name of country'),
    SK: t('COUNTRY_NAME_SK', 'Slovakia', 'Name of country'),
    SI: t('COUNTRY_NAME_SI', 'Slovenia', 'Name of country'),
    SB: t('COUNTRY_NAME_SB', 'Solomon Islands', 'Name of country'),
    SO: t('COUNTRY_NAME_SO', 'Somalia', 'Name of country'),
    ZA: t('COUNTRY_NAME_ZA', 'South Africa', 'Name of country'),
    GS: t(
      'COUNTRY_NAME_GS',
      'South Georgia and the South Sandwich Islands',
      'Name of country',
    ),
    ES: t('COUNTRY_NAME_ES', 'Spain', 'Name of country'),
    LK: t('COUNTRY_NAME_LK', 'Sri Lanka', 'Name of country'),
    SD: t('COUNTRY_NAME_SD', 'Sudan', 'Name of country'),
    SR: t('COUNTRY_NAME_SR', 'Suriname', 'Name of country'),
    SJ: t('COUNTRY_NAME_SJ', 'Svalbard And Jan Mayen', 'Name of country'),
    SZ: t('COUNTRY_NAME_SZ', 'Eswatini', 'Name of country'),
    SE: t('COUNTRY_NAME_SE', 'Sweden', 'Name of country'),
    CH: t('COUNTRY_NAME_CH', 'Switzerland', 'Name of country'),
    SY: t('COUNTRY_NAME_SY', 'Syrian Arab Republic', 'Name of country'),
    TW: t('COUNTRY_NAME_TW', 'Taiwan', 'Name of country'),
    TJ: t('COUNTRY_NAME_TJ', 'Tajikistan', 'Name of country'),
    TZ: t('COUNTRY_NAME_TZ', 'Tanzania', 'Name of country'),
    TH: t('COUNTRY_NAME_TH', 'Thailand', 'Name of country'),
    TL: t('COUNTRY_NAME_TL', 'Timor-Leste', 'Name of country'),
    TG: t('COUNTRY_NAME_TG', 'Togo', 'Name of country'),
    TK: t('COUNTRY_NAME_TK', 'Tokelau', 'Name of country'),
    TO: t('COUNTRY_NAME_TO', 'Tonga', 'Name of country'),
    TT: t('COUNTRY_NAME_TT', 'Trinidad And Tobago', 'Name of country'),
    TN: t('COUNTRY_NAME_TN', 'Tunisia', 'Name of country'),
    TR: t('COUNTRY_NAME_TR', 'Turkey', 'Name of country'),
    TM: t('COUNTRY_NAME_TM', 'Turkmenistan', 'Name of country'),
    TC: t('COUNTRY_NAME_TC', 'Turks And Caicos Islands', 'Name of country'),
    TV: t('COUNTRY_NAME_TV', 'Tuvalu', 'Name of country'),
    UG: t('COUNTRY_NAME_UG', 'Uganda', 'Name of country'),
    UA: t('COUNTRY_NAME_UA', 'Ukraine', 'Name of country'),
    AE: t('COUNTRY_NAME_AE', 'United Arab Emirates', 'Name of country'),
    GB: t('COUNTRY_NAME_GB', 'United Kingdom', 'Name of country'),
    US: t('COUNTRY_NAME_US', 'United States', 'Name of country'),
    UM: t(
      'COUNTRY_NAME_UM',
      'United States Outlying Islands',
      'Name of country',
    ),
    UY: t('COUNTRY_NAME_UY', 'Uruguay', 'Name of country'),
    UZ: t('COUNTRY_NAME_UZ', 'Uzbekistan', 'Name of country'),
    VU: t('COUNTRY_NAME_VU', 'Vanuatu', 'Name of country'),
    VE: t('COUNTRY_NAME_VE', 'Venezuela', 'Name of country'),
    VN: t('COUNTRY_NAME_VN', 'Vietnam', 'Name of country'),
    VG: t('COUNTRY_NAME_VG', 'Virgin Islands, British', 'Name of country'),
    VI: t('COUNTRY_NAME_VI', 'Virgin Islands, U.S.', 'Name of country'),
    WF: t('COUNTRY_NAME_WF', 'Wallis And Futuna', 'Name of country'),
    EH: t('COUNTRY_NAME_EH', 'Western Sahara', 'Name of country'),
    YE: t('COUNTRY_NAME_YE', 'Yemen', 'Name of country'),
    ZM: t('COUNTRY_NAME_ZM', 'Zambia', 'Name of country'),
    ZW: t('COUNTRY_NAME_ZW', 'Zimbabwe', 'Name of country'),
  };
}
