export const LOG_USER_ACTION = 'LOG_USER_ACTION';
export const LOG_TAGGABLE_ACTION = 'LOG_TAGGABLE_ACTION';
export const LOG_FB_ACTION = 'LOG_FB_ACTION';

// Google Analytics
export const GA_PARTNER_ID_RECEIVED = 'GA_PARTNER_ID_RECEIVED';
export const GA_PARTNER_ID_FETCH_FAILED = 'GA_PARTNER_ID_FETCH_FAILED';

// Qualaroo
export const FETCH_QUALAROO_PARTNER_ID = 'FETCH_QUALAROO_PARTNER_ID';
export const QUALAROO_PARTNER_ID_RECEIVED = 'QUALAROO_PARTNER_ID_RECEIVED';
export const QUALAROO_PARTNER_ID_FETCH_FAILED =
  'QUALAROO_PARTNER_ID_FETCH_FAILED';

// Qualtrics
export const FETCH_QUALTRICS_PARTNER_ID = 'FETCH_QUALTRICS_PARTNER_ID';
export const QUALTRICS_PARTNER_ID_RECEIVED = 'QUALTRICS_PARTNER_ID_RECEIVED';
export const QUALTRICS_PARTNER_ID_FETCH_FAILED =
  'QUALTRICS_PARTNER_ID_FETCH_FAILED';

// MIA Conversion pixel
export const TRACK_CONVERSION_ACTION = 'TRACK_CONVERSION_ACTION';

// Semantic Metrics
export const SEND_SEMANTIC_METRIC = 'SEND_SEMANTIC_METRIC';
