export const FETCH_STOCK_MUSIC_SUCCESS = 'FETCH_STOCK_MUSIC_SUCCESS';
export const FETCH_STOCK_MUSIC_FAILED = 'FETCH_STOCK_MUSIC_FAILED';
export const FETCH_STOCK_MUSIC_REQUESTED = 'FETCH_STOCK_MUSIC_REQUESTED';
