export const SET_SIGNUP_ALERT = 'SET_SIGNUP_ALERT';
export const CREATE_ACCOUNT_REQUESTED = 'CREATE_ACCOUNT_REQUESTED';
export const CREATE_ACCOUNT_SUCCEEDED = 'CREATE_ACCOUNT_SUCCEEDED';
export const CREATE_ACCOUNT_FAILED = 'CREATE_ACCOUNT_FAILED';
