export const FETCH_AD_ACCOUNT_REDIRECT_REQUESTED =
  'FETCH_AD_ACCOUNT_REDIRECT_REQUESTED';
export const FETCH_AD_ACCOUNT_REDIRECT_SUCCESS =
  'FETCH_AD_ACCOUNT_REDIRECT_SUCCESS';
export const FETCH_AD_ACCOUNT_REDIRECT_FAILED =
  'FETCH_AD_ACCOUNT_REDIRECT_FAILED';
