export const ALL_ONBOARDING_STEPS_VIEWED = 'ALL_ONBOARDING_STEPS_VIEWED';
export const SET_USER_ONBOARDED = 'SET_USER_ONBOARDED';
export const RESET_USER_ONBOARDED = 'RESET_USER_ONBOARDED';
export const USER_HAS_ALREADY_BEEN_ONBOARDED = 'USER_HAS_BEEN_ONBOARDED';
export const CLOSE_ONBOARDING_MODAL = 'CLOSE_ONBOARDING_MODAL';
export const USER_REQUESTS_ONBOARDING_AGAIN = 'USER_REQUESTS_ONBOARDING_AGAIN';
export const GO_TO_NEXT_HIERARCHY_ONBOARDING_STAGE =
  'GO_TO_NEXT_HIERARCHY_ONBOARDING_STAGE';
export const REQUEST_ACCOUNT_HIERARCHY_ONBOARDING =
  'REQUEST_ACCOUNT_HIERARCHY_ONBOARDING';
export const SET_ACCOUNT_HIERARCHY_ONBOARDING_STATE =
  'SET_ACCOUNT_HIERARCHY_ONBOARDING_STATE';
export const SET_USER_SEEN_COPY_EXISTING_ONBOARDING =
  'SET_USER_SEEN_COPY_EXISTING_ONBOARDING';
export const FETCH_USER_HAS_SEEN_COPY_EXISTING_ONBOARDING =
  'FETCH_USER_HAS_SEEN_COPY_EXISTING_ONBOARDING';
export const FETCH_USER_HAS_SEEN_AD_SET_DUPE_ONBOARDING =
  'FETCH_USER_HAS_SEEN_AD_SET_DUPE_ONBOARDING';
export const SET_USER_HAS_SEEN_AD_SET_DUPE_ONBOARDING =
  'SET_USER_HAS_SEEN_AD_SET_DUPE_ONBOARDING';
export const FETCH_USER_HAS_SEEN_HIERARCHY_DRAFTS_ONBOARDING =
  'FETCH_USER_HAS_SEEN_HIERARCHY_DRAFTS_ONBOARDING';
export const SET_USER_HAS_SEEN_HIERARCHY_DRAFTS_ONBOARDING =
  'SET_USER_HAS_SEEN_HIERARCHY_DRAFTS_ONBOARDING';
export const FETCH_USER_HAS_SEEN_BULKSHEETS_ONBOARDING =
  'FETCH_USER_HAS_SEEN_BULKSHEETS_ONBOARDING';
export const SET_USER_HAS_SEEN_BULKSHEETS_ONBOARDING =
  'SET_USER_HAS_SEEN_BULKSHEETS_ONBOARDING';
export const SHOW_BULKSHEET_ONBOARDING_PHASE =
  'SHOW_BULKSHEET_ONBOARDING_PHASE';

export enum BulksheetOnboardingPhase {
  TABLE_ROW = 'TABLE_ROW',
  ACTION_BAR = 'ACTION_BAR',
  UPLOAD_BTN = 'UPLOAD_BTN',
}
